[build]
  functions = "service"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_POLICY_ROOT = "Policy root"
  POLICY_ID = "Policy ID"
  TENANT_ID = "Aserto tenant ID"
  AUTHORIZER_API_KEY = "Aserto authorizer API key"
  REACT_APP_NETLIFY = "Netlify flag must be set to NETLIFY"
  AUTHORIZER_SERVICE_URL=https://authorizer.prod.aserto.com
  AUTH0_SECRET="Your Auth0 Secret"
  AUTH0_ISSUER_BASE_URL=https://aserto-demo.us.auth0.com
  AUTH0_CLIENT_ID= "Auth0 Client ID "
  AUTH0_CLIENT_SECRET= "Auth0 Client Secret "
  AUTH0_AUDIENCE= "Auth0 Audience "
  AUTH0_SCOPE= "openid profile "
